=== ZLLselfRedeem/zllinmitu/MituWork/MituTools/ToolkitSuite/Xml/schema/v4/Theme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by lzm (baison) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tk="http://www.qdocuments.net" elementFormDefault="qualified">
	<xs:include schemaLocation="../bin/CommonType.xsd"/>
	<xs:element name="Toolkit">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Theme">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="ResourceDictionary" type="xs:anyURI"/>
						</xs:sequence>
						<xs:attributeGroup ref="RegItem"/>
						<xs:attribute name="DisplayName" type="xs:string"/>
						<xs:attribute name="Type" default="None">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="None"/>
									<xs:enumeration value="Base"/>
									<xs:enumeration value="Default"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="IsEnabled" type="xs:boolean" default="true"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ZLLselfRedeem/zllinmitu/MituWork/MituTools/ToolkitSuite/Xml/Resources/Themes/Metro/Theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<Toolkit xmlns:tk="http://www.qdocuments.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\schema\v4\Theme.xsd">
	<Theme RegName="Metro">
		<ResourceDictionary>../Normal/Theme.xaml</ResourceDictionary>
		<ResourceDictionary>Brushes.xaml</ResourceDictionary>
		<ResourceDictionary>Fonts.xaml</ResourceDictionary>
		<ResourceDictionary>CoreStyles.xaml</ResourceDictionary>
		<ResourceDictionary>SDKStyles.xaml</ResourceDictionary>
		<ResourceDictionary>Styles.xaml</ResourceDictionary>
	</Theme>
</Toolkit>

=== ZLLselfRedeem/zllinmitu/MituWork/MituTools/ToolkitSuite/Xml/Resources/Themes/Base/Theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<Toolkit xmlns:tk="http://www.qdocuments.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\schema\v4\Theme.xsd">
	<Theme RegName="Base" Type="Base">
	<ResourceDictionary>Brushes_NormalColor.xaml</ResourceDictionary>
	<!--ResourceDictionary>Buttons_NormalColor.xaml</ResourceDictionary-->
		<ResourceDictionary>TimePicker.xaml</ResourceDictionary>
		<ResourceDictionary>DockPanelSplitter.xaml</ResourceDictionary>
		<ResourceDictionary>ImageView.xaml</ResourceDictionary>
		<!--ResourceDictionary>NumericUpDown.xaml</ResourceDictionary-->
		<ResourceDictionary>ColorCanvas.xaml</ResourceDictionary>
		<ResourceDictionary>ColorPicker.xaml</ResourceDictionary>
		<ResourceDictionary>All.xaml</ResourceDictionary>
    <ResourceDictionary>DataGridWithGroupStyle.xaml</ResourceDictionary>
	</Theme>
</Toolkit>
